import { defineConfig } from "vite";

export default defineConfig({
  build: {
    emptyOutDir: false,
    minify: false,
    outDir: "src/imagegen/static",
    rollupOptions: {
      input: "src/imagegen/frontend/main.js",
      output: {
        banner:
          "// Generated by `npm run js:build` from src/imagegen/frontend/main.js.\n// Do not edit this file directly.",
        entryFileNames: "app.js",
        format: "iife",
      },
    },
    sourcemap: true,
  },
  test: {
    environment: "jsdom",
    globals: false,
  },
});
